//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicResxVs2017Registrator.Assets
{
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class for looking up localized (formatted) strings.
    /// </summary>
    /// <remarks>
    /// This class was auto-generated by the PublicResXFileCodeGeneratorEx custom tool.
    ///To add or remove a member, edit your .ResX file then rerun the PublicResXFileCodeGeneratorEx custom tool or rebuild your Visual Studio project.
    /// 
    ///Note: For the purpose of formatted strings the following rules apply:
    ///    1) The comment column (in the resx file) is used to define the type and parameter name. 
    ///    2) The general format is: {FormatType} {ParmName}[, {FormatType} {ParmName}]
    ///    3) Can include xml param comments, i.e. "///".
    ///    4) Can include C# line comments, ie. "//" normally used to help translators.
    ///    5) Valid FormatTypes are: string, int, long, bool, datetime, char, byte, float, double, decimal, short, sbyte, ushort, uint, ulong. 
    ///        Note: Object is not a valid format string type. Please use one of the supported types.
    ///    6) Can exclude format and parameter checking by defining $exclude$ in the comment column.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXFileCodeGeneratorEx.PublicResXFileCodeGeneratorEx", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Test
    {
        
        protected Test()
        {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(_resourceManager, null))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PublicResxVs2017Registrator.Assets.Test", typeof(Test).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        ///resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return _culture;
            }
            set
            {
                _culture = value;
            }
        }
        
        /// <summary>
        /// Replaces the format item in a specified <see cref="String"/> with the text equivalent
        ///of the value of a corresponding <see cref="Object"/> instance in a specified array.
        /// </summary>
        public static string Format(string format, params object[] args)
        {
            return string.Format(Culture, format, args);
        }
        
        /// <summary>
        /// Formats a string similar to 'Hi my name is {0} and I am {1} years old.'.
        /// </summary>
        public static string String1(string name, int age)
        {
            return Format(Raw.String1, name, age);
        }
        
        /// <summary>
        /// Formats a string similar to 'Invalid class name &apos;{0}&apos;.'.
        /// </summary>
        public static string Test12345(string className)
        {
            return Format(Raw.Test12345, className);
        }
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static global::System.Globalization.CultureInfo _culture;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXFileCodeGeneratorEx.PublicResXFileCodeGeneratorEx", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public partial class Raw
        {
            
            private Raw()
            {
            }
            
            /// <summary>
            /// Looks up a localized string similar to 'Hi my name is {0} and I am {1} years old.'.
            /// </summary>
            public static string String1
            {
                get
                {
                    return ResourceManager.GetString("String1", Culture);
                }
            }
            
            /// <summary>
            /// Looks up a localized string similar to 'Invalid class name &apos;{0}&apos;.'.
            /// </summary>
            public static string Test12345
            {
                get
                {
                    return ResourceManager.GetString("Test12345", Culture);
                }
            }
        }
    }
}
